version: "3.9"

services:

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fastapi

    ports:
      - "8000:8000"

    depends_on:
      - redis

    volumes:
      - .:/app

    environment:
      REDIS_URL: redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: celery

    depends_on:
      - redis

    command: >
      celery
      -A app.celery.celery_app.celery_app
      worker
      --loglevel=info
      --concurrency=4

    volumes:
      - .:/app

    environment:
      REDIS_URL: redis://redis:6379/0

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    container_name: streamlit

    ports:
      - "8501:8501"

    depends_on:
      - backend